//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.02 at 03:12:07 PM CEST 
//


package hu.gdf.oop.fogadoiroda.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hu.gdf.oop.fogadoiroda.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OpenEventsResponse_QNAME = new QName("http://xml.fogadoiroda.oop.gdf.hu/", "openEventsResponse");
    private final static QName _Echo_QNAME = new QName("http://xml.fogadoiroda.oop.gdf.hu/", "echo");
    private final static QName _OpenEvents_QNAME = new QName("http://xml.fogadoiroda.oop.gdf.hu/", "openEvents");
    private final static QName _EchoResponse_QNAME = new QName("http://xml.fogadoiroda.oop.gdf.hu/", "echoResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hu.gdf.oop.fogadoiroda.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OpenEventsResponse }
     * 
     */
    public OpenEventsResponse createOpenEventsResponse() {
        return new OpenEventsResponse();
    }

    /**
     * Create an instance of {@link Echo }
     * 
     */
    public Echo createEcho() {
        return new Echo();
    }

    /**
     * Create an instance of {@link OpenEvents }
     * 
     */
    public OpenEvents createOpenEvents() {
        return new OpenEvents();
    }

    /**
     * Create an instance of {@link EchoResponse }
     * 
     */
    public EchoResponse createEchoResponse() {
        return new EchoResponse();
    }

    /**
     * Create an instance of {@link Outcomes }
     * 
     */
    public Outcomes createOutcomes() {
        return new Outcomes();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link Events }
     * 
     */
    public Events createEvents() {
        return new Events();
    }

    /**
     * Create an instance of {@link Outcome }
     * 
     */
    public Outcome createOutcome() {
        return new Outcome();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpenEventsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.fogadoiroda.oop.gdf.hu/", name = "openEventsResponse")
    public JAXBElement<OpenEventsResponse> createOpenEventsResponse(OpenEventsResponse value) {
        return new JAXBElement<OpenEventsResponse>(_OpenEventsResponse_QNAME, OpenEventsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Echo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.fogadoiroda.oop.gdf.hu/", name = "echo")
    public JAXBElement<Echo> createEcho(Echo value) {
        return new JAXBElement<Echo>(_Echo_QNAME, Echo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpenEvents }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.fogadoiroda.oop.gdf.hu/", name = "openEvents")
    public JAXBElement<OpenEvents> createOpenEvents(OpenEvents value) {
        return new JAXBElement<OpenEvents>(_OpenEvents_QNAME, OpenEvents.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EchoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.fogadoiroda.oop.gdf.hu/", name = "echoResponse")
    public JAXBElement<EchoResponse> createEchoResponse(EchoResponse value) {
        return new JAXBElement<EchoResponse>(_EchoResponse_QNAME, EchoResponse.class, null, value);
    }

}
