//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.22 at 03:08:10 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xml.fogadoiroda.oop.gdf.hu/")
package hu.gdf.oop.fogadoiroda.xml;
