package hu.gdf.oop.fogadoiroda.gui;

import java.awt.CardLayout;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author marci
 */
public class ApplicationGUI extends javax.swing.JFrame {

    /**
     * Creates new form ApplicationGUI
     */
    public ApplicationGUI() {
        initComponents();
        ((CardLayout) mainPanel.getLayout()).show(mainPanel, "card2");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        lLogin = new javax.swing.JLabel();
        lPassword = new javax.swing.JLabel();
        tfLogin = new javax.swing.JTextField();
        pfPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usersPanel = new hu.gdf.oop.fogadoiroda.gui.UsersPanel();
        betEventsPanel = new hu.gdf.oop.fogadoiroda.gui.BetEventsPanel();
        mBar = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        mLogout = new javax.swing.JMenuItem();
        mExit = new javax.swing.JMenuItem();
        mTables = new javax.swing.JMenu();
        mUsers = new javax.swing.JMenuItem();
        mBetEvents = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fogadóiroda backoffice alkalmazás");

        mainPanel.setLayout(new java.awt.CardLayout());

        loginPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Bejelentkezés"));
        loginPanel.setLayout(new java.awt.GridBagLayout());

        lLogin.setText("Login:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 5, 0, 0);
        loginPanel.add(lLogin, gridBagConstraints);

        lPassword.setText("Jelszó:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 3, 0, 0);
        loginPanel.add(lPassword, gridBagConstraints);

        tfLogin.setPreferredSize(new java.awt.Dimension(150, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 140;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 336);
        loginPanel.add(tfLogin, gridBagConstraints);

        pfPassword.setPreferredSize(new java.awt.Dimension(150, 26));
        pfPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pfPasswordKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 140;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 336);
        loginPanel.add(pfPassword, gridBagConstraints);

        btnLogin.setText("Belépés");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 41, 0, 0);
        loginPanel.add(btnLogin, gridBagConstraints);

        btnReset.setText("Reset");
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        loginPanel.add(btnReset, gridBagConstraints);

        jLabel1.setText("Kérjük adja meg a belépési adatait!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 41, 0, 0);
        loginPanel.add(jLabel1, gridBagConstraints);

        jLabel2.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 41, 298, 0);
        loginPanel.add(jLabel2, gridBagConstraints);

        mainPanel.add(loginPanel, "login");
        mainPanel.add(usersPanel, "users");
        mainPanel.add(betEventsPanel, "betEvents");

        mFile.setText("Fájl");

        mLogout.setText("Kijelentkezés");
        mLogout.setEnabled(false);
        mLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLogoutActionPerformed(evt);
            }
        });
        mFile.add(mLogout);

        mExit.setText("Kilépés");
        mExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mExitActionPerformed(evt);
            }
        });
        mFile.add(mExit);

        mBar.add(mFile);

        mTables.setText("Táblák");

        mUsers.setText("Felhasználók");
        mUsers.setEnabled(false);
        mUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mUsersActionPerformed(evt);
            }
        });
        mTables.add(mUsers);

        mBetEvents.setText("Fogadások");
        mBetEvents.setEnabled(false);
        mBetEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mBetEventsActionPerformed(evt);
            }
        });
        mTables.add(mBetEvents);

        mBar.add(mTables);

        setJMenuBar(mBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mUsersActionPerformed
        usersPanel.loadData();
        ((CardLayout) mainPanel.getLayout()).show(mainPanel, "users");
    }//GEN-LAST:event_mUsersActionPerformed

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        tfLogin.setText("");
        pfPassword.setText("");
    }//GEN-LAST:event_btnResetMouseClicked

    private void mBetEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mBetEventsActionPerformed
        ((CardLayout) mainPanel.getLayout()).show(mainPanel, "betEvents");
    }//GEN-LAST:event_mBetEventsActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        doLogin();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void mLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mLogoutActionPerformed
        mLogout.setEnabled(false);
        mUsers.setEnabled(false);
        mBetEvents.setEnabled(false);
    }//GEN-LAST:event_mLogoutActionPerformed

    private void mExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mExitActionPerformed

    private void pfPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfPasswordKeyPressed
        System.out.println(evt.getKeyCode());
        if (evt.getKeyCode() == 10) {
            doLogin();
        }
    }//GEN-LAST:event_pfPasswordKeyPressed

    private void doLogin() {
        tfLogin.setEnabled(false);
        pfPassword.setEnabled(false);
        btnLogin.setEnabled(false);
        btnReset.setEnabled(false);
        try {
            Thread.sleep(500);
        } catch (InterruptedException ex) {
            Logger.getLogger(ApplicationGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        String passString = new String(pfPassword.getPassword());
        if ("".equals(passString)) {
            jLabel2.setForeground(Color.RED);
            jLabel2.setText("A megadott felhasználónév és/vagy jelszó érvénytelen!");
        } else {
            jLabel2.setForeground(Color.BLUE);
            jLabel2.setText("Sikeres belépés");
            mLogout.setEnabled(true);
            mUsers.setEnabled(true);
            mBetEvents.setEnabled(true);
            tfLogin.setText("");
            pfPassword.setText("");
        }
        tfLogin.setEnabled(true);
        pfPassword.setEnabled(true);
        btnLogin.setEnabled(true);
        btnReset.setEnabled(true);        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplicationGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private hu.gdf.oop.fogadoiroda.gui.BetEventsPanel betEventsPanel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lLogin;
    private javax.swing.JLabel lPassword;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JMenuBar mBar;
    private javax.swing.JMenuItem mBetEvents;
    private javax.swing.JMenuItem mExit;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenuItem mLogout;
    private javax.swing.JMenu mTables;
    private javax.swing.JMenuItem mUsers;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField tfLogin;
    private hu.gdf.oop.fogadoiroda.gui.UsersPanel usersPanel;
    // End of variables declaration//GEN-END:variables
}
